AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for creating Cognito User Pool

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
    Description: "Deployment environment. Allowed values are 'dev' or 'prod'."
  ResourceBaseIdentifier:
    Type: String
    Description: "Base identifier for resource naming."

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${ResourceBaseIdentifier}-userpool-${Environment}"
      AliasAttributes:
        - email
        - preferred_username
      AutoVerifiedAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      MfaConfiguration: "OFF"

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${ResourceBaseIdentifier}-client-${Environment}"
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH

Outputs:
  CognitoUserPoolId:
    Value: !Ref CognitoUserPool
    Description: "Cognito User Pool ID"
    Export:
      Name: !Sub "${AWS::StackName}-CognitoUserPoolId"

  CognitoUserPoolClientId:
    Value: !Ref CognitoUserPoolClient
    Description: "Cognito User Pool Client ID"
    Export:
      Name: !Sub "${AWS::StackName}-CognitoUserPoolClientId"
