AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SageMaker Serverless Inference for OpenCLIP (HuggingFace-based model).

Parameters:
  Environment:
    Type: String
    Description: Deployment environment (e.g., dev, prod).

Resources:
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "oai-c-sagemaker-exec-role-${Environment}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: HuggingFaceSageMakerPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                Resource: "*"

  OpenClipModel:
    Type: AWS::SageMaker::Model
    Properties:
      ModelName: !Sub "oai-c-model-${Environment}"
      ExecutionRoleArn: !GetAtt SageMakerExecutionRole.Arn
      PrimaryContainer:
        Image: 763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:2.1.0-transformers4.37.0-cpu-py310-ubuntu22.04
        Environment:
          HF_MODEL_ID: "openai/clip-vit-base-patch32"
          HF_TASK: "zero-shot-image-classification"

  OpenClipEndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    DependsOn: OpenClipModel
    Properties:
      EndpointConfigName: !Sub "oai-c-config-${Environment}"
      ProductionVariants:
        - ModelName: !Sub "oai-c-model-${Environment}"
          VariantName: AllTraffic
          ServerlessConfig:
            MaxConcurrency: 5
            MemorySizeInMB: 2048

  OpenClipEndpoint:
    Type: AWS::SageMaker::Endpoint
    Properties:
      EndpointName: !Sub "oai-c-endpoint-${Environment}"
      EndpointConfigName: !Ref OpenClipEndpointConfig

Outputs:
  OpenClipEndpointName:
    Description: Name of the SageMaker Serverless Inference Endpoint
    Value: !Ref OpenClipEndpoint
