AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SageMaker Serverless Inference for OpenCLIP (HuggingFace-based model).

Parameters:
  Environment:
    Type: String
    Description: Deployment environment (e.g., dev, prod).
  ResourceBaseIdentifier:
    Type: String
    Description: Base name prefix for resources.
  ModelBucketName:
    Type: String
    Description: "The S3 bucket containing the OpenCLIP model artifact."

Resources:
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ResourceBaseIdentifier}-sagemaker-exec-role-${Environment}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      Policies:
        - PolicyName: HuggingFaceSageMakerPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub "arn:aws:s3:::${ModelBucketName}/*"

  OpenClipModel:
    Type: AWS::SageMaker::Model
    Properties:
      ModelName: !Sub "${ResourceBaseIdentifier}-openclip-${Environment}"
      ExecutionRoleArn: !GetAtt SageMakerExecutionRole.Arn
      PrimaryContainer:
        Image: 763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:2.1.0-transformers4.37.0-cpu-py310-ubuntu22.04
        ModelDataUrl: !Sub "s3://${ModelBucketName}/model.tar.gz"
        Environment:
          HF_MODEL_ID: "openai/clip-vit-base-patch32"
          HF_TASK: "feature-extraction"

  OpenClipEndpointConfig:
    Type: AWS::SageMaker::EndpointConfig
    DependsOn: OpenClipModel
    Properties:
      EndpointConfigName: !Sub "${ResourceBaseIdentifier}-openclip-config-${Environment}"
      ProductionVariants:
        - ModelName: !Sub "${ResourceBaseIdentifier}-openclip-${Environment}"
          VariantName: AllTraffic
          ServerlessConfig:
            MaxConcurrency: 5
            MemorySizeInMB: 3072

  OpenClipEndpoint:
    Type: AWS::SageMaker::Endpoint
    DependsOn: OpenClipEndpointConfig
    Properties:
      EndpointName: !Sub "${ResourceBaseIdentifier}-openclip-endpoint-${Environment}"
      EndpointConfigName: !Sub "${ResourceBaseIdentifier}-openclip-config-${Environment}"

Outputs:
  SageMakerEndointName:
    Description: Name of the SageMaker Serverless Inference Endpoint
    Value: !GetAtt OpenClipEndpoint.EndpointName
    Export:
      Name: !Sub "${ResourceBaseIdentifier}-OpenClipEndpointName-${Environment}"
