AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for the entire application

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
    Description: "Deployment environment. Allowed values are 'dev' or 'prod'."
  ResourceBaseIdentifier:
    Type: String
    Description: "Base identifier for resource naming."
  DeploymentRoleARN:
    Type: String
    Description: "ARN of the IAM role for deployment."

Resources:
  # S3 Nested Stack
  S3:
    Type: AWS::Serverless::Application
    Properties:
      Location: s3.yml
      Parameters:
        Environment: !Ref Environment
        ResourceBaseIdentifier: !Ref ResourceBaseIdentifier

  # Cognito Nested Stack
  Cognito:
    Type: AWS::Serverless::Application
    Properties:
      Location: cognito.yml
      Parameters:
        Environment: !Ref Environment
        ResourceBaseIdentifier: !Ref ResourceBaseIdentifier

  # Database Nested Stack
  DB:
    Type: AWS::Serverless::Application
    Properties:
      Location: db.yml
      Parameters:
        Environment: !Ref Environment
        ResourceBaseIdentifier: !Ref ResourceBaseIdentifier

  # OpenClip SageMaker Inference Nested Stack
  OpenClipInferenceEndpoint:
    Type: AWS::Serverless::Application
    Properties:
      Location: open_clip_sagemaker_inference.yml
      Parameters:
        Environment: !Ref Environment
        ResourceBaseIdentifier: !Ref ResourceBaseIdentifier
        OpenClipImageBucketArn: !GetAtt S3.Outputs.OpenClipImageBucketArn

  # API Nested Stack
  API:
    Type: AWS::Serverless::Application
    Properties:
      Location: api.yml
      Parameters:
        Environment: !Ref Environment
        ResourceBaseIdentifier: !Ref ResourceBaseIdentifier
        CognitoUserPoolId: !GetAtt Cognito.Outputs.CognitoUserPoolId
        CognitoUserPoolClientId: !GetAtt Cognito.Outputs.CognitoUserPoolClientId
        OpenClipEndpointName: !GetAtt OpenClipInferenceEndpoint.Outputs.OpenClipEndpointName
        OpenClipImageBucketArn: !GetAtt S3.Outputs.OpenClipImageBucketArn
